// <auto-generated />
using System;
using College.Services.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace College.Migrations
{
    [DbContext(typeof(ClgDbContext))]
    [Migration("20251222074240_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("College.Entities.AQARReport", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_Order")
                        .HasColumnType("int");

                    b.Property<string>("S_AcademicYear")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ReportTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("AQARReport");
                });

            modelBuilder.Entity("College.Entities.CampusInfo", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_Count")
                        .HasColumnType("int");

                    b.Property<string>("S_Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("CampusInfo");
                });

            modelBuilder.Entity("College.Entities.ClubsDetails", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("F_ClubsMasterId")
                        .HasColumnType("int");

                    b.Property<int>("I_DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("S_Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Heading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ShortContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("ClubsDetails");
                });

            modelBuilder.Entity("College.Entities.ClubsMaster", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("S_Clubs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("ClubsMaster");
                });

            modelBuilder.Entity("College.Entities.DepartmentsDetails", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("F_DepartmentsMasterId")
                        .HasColumnType("int");

                    b.Property<int>("I_DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("S_Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Heading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ShortContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("DepartmentsDetails");
                });

            modelBuilder.Entity("College.Entities.DepartmentsMaster", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_Department")
                        .HasColumnType("int");

                    b.Property<string>("S_Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Order")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("DepartmentsMaster");
                });

            modelBuilder.Entity("College.Entities.DepartmentsMembers", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("F_DepartmentsMasterId")
                        .HasColumnType("int");

                    b.Property<int>("I_Name")
                        .HasColumnType("int");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Designation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Order")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("DepartmentsMembers");
                });

            modelBuilder.Entity("College.Entities.IQACMembers", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_Order")
                        .HasColumnType("int");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Designation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("IQACMembers");
                });

            modelBuilder.Entity("College.Entities.InstitutionPages", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("S_Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Heading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_PageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("InstitutionPages");
                });

            modelBuilder.Entity("College.Entities.LatestNews", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("D_Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Heading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ShortContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("LatestNews");
                });

            modelBuilder.Entity("College.Entities.Login", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("College.Entities.Management", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Designation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("Management");
                });

            modelBuilder.Entity("College.Entities.ManagementContent", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("F_ManagementId")
                        .HasColumnType("int");

                    b.Property<string>("S_Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("ManagementContent");
                });

            modelBuilder.Entity("College.Entities.MenuMaster", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<string>("B_Display")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("F_ParentMenuId")
                        .HasColumnType("int");

                    b.Property<int>("I_Order")
                        .HasColumnType("int");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_MenuName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_MenuUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("MenuMaster");
                });

            modelBuilder.Entity("College.Entities.NAACDetails", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_Order")
                        .HasColumnType("int");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("NAACDetails");
                });

            modelBuilder.Entity("College.Entities.NAACDocument", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_Order")
                        .HasColumnType("int");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("NAACDocument");
                });

            modelBuilder.Entity("College.Entities.NIRFDetails", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_Order")
                        .HasColumnType("int");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("NIRFDetails");
                });

            modelBuilder.Entity("College.Entities.NIRFDocument", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_Order")
                        .HasColumnType("int");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("NIRFDocument");
                });

            modelBuilder.Entity("College.Entities.NIRFDocumentRanking", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_Year")
                        .HasColumnType("int");

                    b.Property<string>("S_Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ParticipationStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_Score")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("NIRFDocumentRanking");
                });

            modelBuilder.Entity("College.Entities.PageMedia", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("I_Id"));

                    b.Property<bool>("B_Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("D_CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("D_ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("I_DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("S_Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_Heading")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("S_ShortContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("I_Id");

                    b.ToTable("PageMedia");
                });
#pragma warning restore 612, 618
        }
    }
}
