// <auto-generated />
using System;
using College.Services.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace College.Migrations
{
    [DbContext(typeof(CLGDbContext))]
    partial class CLGDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("College.Entities.AQARReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_AcademicYear");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_FilePath");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("I_Order");

                    b.Property<string>("ReportTitle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_ReportTitle");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.ToTable("CLG.AQARReport", (string)null);
                });

            modelBuilder.Entity("College.Entities.CampusInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Category");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("I_Count");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.ToTable("CLG.CampusInfo", (string)null);
                });

            modelBuilder.Entity("College.Entities.ClubsDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Category");

                    b.Property<int>("ClubsMasterId")
                        .HasColumnType("int")
                        .HasColumnName("F_ClubsMasterId");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("I_DisplayOrder");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Heading");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_ImagePath");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("ShortContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_ShortContent");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.HasIndex("ClubsMasterId");

                    b.ToTable("CLG.ClubsDetails", (string)null);
                });

            modelBuilder.Entity("College.Entities.ClubsMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clubs")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Clubs");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("I_DisplayOrder");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_FullName");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.ToTable("CLG.ClubsMaster", (string)null);
                });

            modelBuilder.Entity("College.Entities.DepartmentsDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Category");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<int>("DepartmentsMasterId")
                        .HasColumnType("int")
                        .HasColumnName("F_DepartmentsMasterId");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("I_DisplayOrder");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Heading");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_ImagePath");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("ShortContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_ShortContent");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentsMasterId");

                    b.ToTable("CLG.DepartmentsDetails", (string)null);
                });

            modelBuilder.Entity("College.Entities.DepartmentsMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Category");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Department");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Description");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_ImagePath");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("I_Order");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int")
                        .HasColumnName("S_StudentCount");

                    b.Property<string>("SyllabusPath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_SyllabusPath");

                    b.HasKey("Id");

                    b.ToTable("CLG.DepartmentsMaster", (string)null);
                });

            modelBuilder.Entity("College.Entities.DepartmentsMembers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<int>("DepartmentsMasterId")
                        .HasColumnType("int")
                        .HasColumnName("F_DepartmentsMasterId");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Designation");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_ImagePath");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("I_Order");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentsMasterId");

                    b.ToTable("CLG.DepartmentsMembers", (string)null);
                });

            modelBuilder.Entity("College.Entities.IQACMembers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Designation");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("I_Order");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Role");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.ToTable("CLG.IQACMembers", (string)null);
                });

            modelBuilder.Entity("College.Entities.InstitutionPages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Content");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Heading");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("PageType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_PageType");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.ToTable("CLG.InstitutionPages", (string)null);
                });

            modelBuilder.Entity("College.Entities.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedOn");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("D_IsActive");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_LastLogin");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Password");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_UserId");

                    b.HasKey("Id");

                    b.ToTable("CLG.Login", (string)null);
                });

            modelBuilder.Entity("College.Entities.Management", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Designation");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("I_DisplayOrder");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_ImagePath");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Name");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.ToTable("CLG.Management", (string)null);
                });

            modelBuilder.Entity("College.Entities.ManagementContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Content");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<int>("ManagementId")
                        .HasColumnType("int")
                        .HasColumnName("F_ManagementId");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.HasIndex("ManagementId");

                    b.ToTable("CLG.ManagementContent", (string)null);
                });

            modelBuilder.Entity("College.Entities.MenuMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("B_Display");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_MenuName");

                    b.Property<string>("MenuUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_MenuUrl");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("I_Order");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("int")
                        .HasColumnName("F_ParentMenuId");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.HasIndex("ParentMenuId");

                    b.ToTable("CLG.MenuMaster", (string)null);
                });

            modelBuilder.Entity("College.Entities.NACDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Description");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("I_Order");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.ToTable("CLG.NACDetails", (string)null);
                });

            modelBuilder.Entity("College.Entities.NACDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("I_Order");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Path");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.ToTable("CLG.NACDocument", (string)null);
                });

            modelBuilder.Entity("College.Entities.NIRFDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Description");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("I_Order");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.ToTable("CLG.NIRFDetails", (string)null);
                });

            modelBuilder.Entity("College.Entities.NIRFDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Path");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("I_Year");

                    b.HasKey("Id");

                    b.ToTable("CLG.NIRFDocument", (string)null);
                });

            modelBuilder.Entity("College.Entities.NIRFDocumentRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Category");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("ParticipationStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_ParticipationStatus");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Score");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("I_Year");

                    b.HasKey("Id");

                    b.ToTable("CLG.NIRFDocumentRanking", (string)null);
                });

            modelBuilder.Entity("College.Entities.PageMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Category");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_Date");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("I_DisplayOrder");

                    b.Property<string>("Heading")
                        .HasColumnType("longtext")
                        .HasColumnName("S_Heading");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_ImagePath");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<string>("ShortContent")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ShortContent");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.HasKey("Id");

                    b.ToTable("CLG.PageMedia", (string)null);
                });

            modelBuilder.Entity("College.Entities.SettingMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("I_Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_CreatedDate");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Key");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("S_ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("D_ModifiedDate");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("B_Status");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_Value");

                    b.HasKey("Id");

                    b.ToTable("CLG.SettingMaster", (string)null);
                });

            modelBuilder.Entity("College.Entities.ClubsDetails", b =>
                {
                    b.HasOne("College.Entities.ClubsMaster", null)
                        .WithMany()
                        .HasForeignKey("ClubsMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("College.Entities.DepartmentsDetails", b =>
                {
                    b.HasOne("College.Entities.DepartmentsMaster", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("College.Entities.DepartmentsMembers", b =>
                {
                    b.HasOne("College.Entities.DepartmentsMaster", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("College.Entities.ManagementContent", b =>
                {
                    b.HasOne("College.Entities.Management", null)
                        .WithMany()
                        .HasForeignKey("ManagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("College.Entities.MenuMaster", b =>
                {
                    b.HasOne("College.Entities.MenuMaster", null)
                        .WithMany()
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
